import { readFileSync } from 'node:fs'
import { describe, expect, it } from 'vitest'

describe('SPEC-032 跨平台节点制品工作流', () => {
  it('Node 20 构建脚本兼容 Unix 与 Windows 的 npm CLI 布局，且不再把长期 token 写入包内说明', () => {
    const source = readFileSync('scripts/build-node-dist.cjs', 'utf8')
    expect(source).toContain("'lib', 'node_modules', 'npm', 'bin', 'npm-cli.js'")
    expect(source).toContain(
      "path.dirname(process.execPath), 'node_modules', 'npm', 'bin', 'npm-cli.js'"
    )
    expect(source).not.toContain('AGENT_OS_NODE_TOKEN=<token>')
    expect(source).toContain("require('better-sqlite3')")
    expect(source).toContain("'verify-node-runtime.cjs'")
    expect(source).toContain("'node-update.cjs'")
    expect(source).toContain("stage, '--probe-pty'")
    expect(source).not.toContain("const pty = require('node-pty')")
    const verifier = readFileSync('scripts/verify-node-runtime.cjs', 'utf8')
    expect(verifier).toContain("console.log('✓ node-pty 真实子进程回显通过')")
    expect(verifier).toContain('process.exit(0)')
    expect(source).toContain('npm_node_execpath: process.execPath')
    expect(source).toContain('PATH: `${path.dirname(process.execPath)}')
  })

  it('节点 CLI 升级使用外部原子 bootstrap，不再把 tar 原地解压进当前安装目录', () => {
    const cli = readFileSync('scripts/agentos-cli.cjs', 'utf8')
    const updater = readFileSync('scripts/node-update.cjs', 'utf8')
    expect(cli).toContain('prepareNodeUpdate')
    expect(cli).toContain("process.env.AGENT_OS_NODE_REPO || 'aiutil/agent-os'")
    expect(cli).not.toContain("process.env.AGENT_OS_NODE_REPO || 'lohasle/agent-life'")
    expect(cli).toContain('launchPreparedUpdate')
    expect(cli).not.toContain("curl -fsSL '${url}' | tar -xz")
    expect(updater).toContain('validateReleaseMetadata')
    expect(updater).toContain('fileIntegrityVerified !== true')
    expect(updater).toContain('node-status.json')
    expect(updater).toContain('adoptedAt')
    expect(updater).toContain('主控完成 Runtime/PTY/Agent 接管确认')
    expect(updater).toContain('"$STAGE/agentos-node"')
    expect(updater).toContain('$StageRunner = Join-Path $Stage "run-node.cmd"')
    expect(updater).toContain('goto agentos_restart')
    expect(cli).toContain(':agentos_restart')
    expect(cli).toContain('goto agentos_restart')
    expect(cli).toContain('call "%~dp0agentos-node.cmd"')
    const publicInstaller = readFileSync('scripts/install-node.sh', 'utf8')
    // 公共安装器源码本身就是 heredoc 生产者，必须保留一层转义，避免安装时提前展开。
    expect(publicInstaller).toContain(
      'AGENT_OS_NODE_PREFIX="\\$(CDPATH= cd -P "\\$(dirname "\\$0")" && pwd -P)"'
    )
    expect(publicInstaller).toContain('"\\$AGENT_OS_NODE_PREFIX/out/main/remote-node.js" "\\$@"')
    expect(publicInstaller).not.toContain('export AGENT_OS_NODE_PREFIX="$PREFIX"')
  })

  it('GitHub Actions 在五个原生 runner 产包，汇总后先 dry-run 再按显式开关发布', () => {
    const workflow = readFileSync('.github/workflows/node-runtime-release.yml', 'utf8')
    const attributes = readFileSync('.gitattributes', 'utf8')
    expect(attributes).toContain('scripts/install-node.sh text eol=lf')
    for (const platform of ['mac-arm64', 'mac-x64', 'linux-arm64', 'linux-x64', 'win-x64']) {
      expect(workflow).toContain(`platform: ${platform}`)
    }
    expect(workflow).toContain('node-version: 20.17.0')
    for (const command of [
      'electron-builder --mac dmg --arm64',
      'electron-builder --mac dmg --x64',
      'electron-builder --linux AppImage --arm64',
      'electron-builder --linux AppImage deb --x64',
      'electron-builder --win nsis --x64'
    ])
      expect(workflow).toContain(command)
    expect(workflow).toContain('runner: windows-2022')
    expect(workflow).toContain("python-version: '3.11'")
    expect(workflow).toContain("matrix.platform == 'linux-arm64'")
    expect(workflow).toContain('node scripts/build-linux-deb.cjs')
    expect(workflow).toContain('release/Agent-Os-*')
    expect(workflow).toContain('release/agentos-desktop-*-manifest.json')
    expect(workflow).toContain('node scripts/release-gh.cjs --dry-run')
    expect(workflow).toContain('node scripts/check-public-release-consistency.cjs --pre-publish')
    expect(workflow).toContain('node scripts/release-gh.cjs --repo aiutil/agent-os --stage-only')
    expect(workflow).toContain('node scripts/release-gh.cjs --repo lohasle/agent-life --stage-only')
    expect(workflow).toContain('node scripts/verify-release-mirror.cjs --draft')
    expect(workflow).toContain('node scripts/sync-agent-life-site.cjs --repo-dir')
    expect(workflow).toContain('--site-dir "$GITHUB_WORKSPACE/site"')
    expect(workflow).toContain('--site-dir "$GITHUB_WORKSPACE/site" --check')
    expect(workflow).toContain('node scripts/release-gh.cjs --repo aiutil/agent-os --promote-only')
    expect(workflow).toContain(
      'node scripts/release-gh.cjs --repo lohasle/agent-life --promote-only'
    )
    expect(workflow).toContain('node scripts/verify-release-mirror.cjs')
    expect(workflow).not.toContain('git push origin HEAD:main')
    expect(workflow.indexOf('--repo aiutil/agent-os --stage-only')).toBeLessThan(
      workflow.indexOf('--repo lohasle/agent-life --stage-only')
    )
    expect(workflow.indexOf('--repo lohasle/agent-life --stage-only')).toBeLessThan(
      workflow.indexOf('sync-agent-life-site.cjs')
    )
    expect(workflow.indexOf('sync-agent-life-site.cjs')).toBeLessThan(
      workflow.indexOf('--pre-publish')
    )
    expect(workflow.indexOf('--pre-publish')).toBeLessThan(
      workflow.indexOf('--repo aiutil/agent-os --promote-only')
    )
    expect(workflow.indexOf('--repo aiutil/agent-os --promote-only')).toBeLessThan(
      workflow.indexOf('--repo lohasle/agent-life --promote-only')
    )
    expect(workflow).toContain('npm run verify:release-consistency')
    expect(workflow).toContain('npm run verify:node-release-public')
    expect(workflow).toContain('GH_TOKEN: ${{ secrets.CANONICAL_RELEASE_TOKEN }}')
    expect(workflow).toContain('LEGACY_RELEASE_TOKEN: ${{ secrets.LEGACY_RELEASE_TOKEN }}')
    expect(workflow).toContain('CANONICAL_GH_TOKEN: ${{ secrets.CANONICAL_RELEASE_TOKEN }}')
    expect(workflow).toContain('LEGACY_GH_TOKEN: ${{ secrets.LEGACY_RELEASE_TOKEN }}')
    expect(workflow).not.toContain('AGENT_LIFE_RELEASE_TOKEN')
    expect(workflow).toContain('-c.forceCodeSigning=true')
    expect(workflow).toContain('MACOS_CSC_LINK')
    expect(workflow).toContain('MACOS_CSC_KEY_PASSWORD')
    expect(workflow).not.toContain('APPLE_APP_SPECIFIC_PASSWORD')
    expect(workflow).not.toContain('APPLE_TEAM_ID')
    expect(workflow).toContain('security add-trusted-cert -p codeSign -r trustRoot')
    expect(workflow).not.toContain('security trust-settings-import')
    expect(workflow).toContain('Trust fixed identity in macOS system keychain')
    expect(workflow).toContain('sudo -n security add-trusted-cert')
    expect(workflow).toContain('security set-key-partition-list')
    expect(workflow).toContain('CSC_KEYCHAIN=')
    expect(workflow).toContain('CSC_NAME=Agent OS Self-Signed')
    expect(workflow).toContain('Remove temporary macOS signing material')
    expect(workflow.indexOf('echo "CSC_KEYCHAIN=')).toBeLessThan(
      workflow.indexOf('base64 -D > "$signing_p12"')
    )
    expect(workflow).toContain('node build/verify-macos-release.cjs')
    const macVerifier = readFileSync('build/verify-macos-release.cjs', 'utf8')
    expect(macVerifier).toContain('Authority=Agent OS Self-Signed')
    expect(macVerifier).toContain("'--verify', '--deep', '--strict'")
    expect(macVerifier).not.toContain("'spctl'")
    expect(macVerifier).not.toContain("'stapler'")
    expect(workflow).toContain("github.ref != 'refs/heads/main'")
    expect(workflow).toContain('publish=true is only allowed from refs/heads/main')
    expect(workflow).toContain('release/agentos-release-*-provenance.json')
    const publicConsistency = readFileSync('scripts/check-public-release-consistency.cjs', 'utf8')
    expect(publicConsistency).toContain("asset?.name === 'install-node.sh'")
    expect(publicConsistency).toContain("createHash('sha256')")
    expect(publicConsistency).toContain('provenanceAssetName(version)')
    const releaseScript = readFileSync('scripts/release-gh.cjs', 'utf8')
    expect(releaseScript).toContain('同版本异实现')
    expect(releaseScript).toContain('assertCompatibleProvenance')
    expect(releaseScript).toContain('sourceTreeClean')
    expect(releaseScript).toContain('assertDesktopReleaseArtifacts')
    expect(releaseScript).toContain('requiredDesktopAssets')
    expect(releaseScript).toContain('requiredDesktopManifests')
    expect(releaseScript).toContain('requiredNodeAssets')
    expect(releaseScript).toContain('releaseSourceMarker')
    expect(releaseScript).toContain('waitForVerifiedRelease(expectedAssets, true)')
    expect(releaseScript).toContain("'--draft'")
    expect(releaseScript).toContain("'--draft=false', '--latest'")
    expect(releaseScript).toContain('assertRemoteReleaseMatches')
    expect(releaseScript).toContain('assertPublishSource')
    expect(releaseScript).toContain("'status', '--porcelain', '--untracked-files=all'")
    expect(releaseScript).toContain("'remote', 'get-url', 'origin'")
    expect(releaseScript).toContain('`repos/${CANONICAL_REPO}/git/ref/heads/main`')
    expect(releaseScript).toContain("process.argv.includes('--stage-only')")
    expect(releaseScript).toContain("process.argv.includes('--promote-only')")
    expect(releaseScript).toContain("const LEGACY_REPO = 'lohasle/agent-life'")
    expect(releaseScript).toContain('ALLOWED_RELEASE_REPOS')
    expect(releaseScript).toContain("REPO === LEGACY_REPO && version !== '0.3.9'")
    expect(releaseScript).toContain('REPO === CANONICAL_REPO')
    const mirrorVerifier = readFileSync('scripts/verify-release-mirror.cjs', 'utf8')
    expect(mirrorVerifier).toContain("const CANONICAL_REPO = 'aiutil/agent-os'")
    expect(mirrorVerifier).toContain("const LEGACY_REPO = 'lohasle/agent-life'")
    expect(mirrorVerifier).toContain('GH_TOKEN: tokenFor(repo)')
    expect(mirrorVerifier).toContain('canonical and legacy asset name/size/SHA-256 sets differ')
    expect(releaseScript).toContain(
      'if (hasNodeAssets && !promoteOnly && !reusedPublishedManifest)'
    )
    expect(releaseScript).toContain('AGENTOS_REUSE_EXISTING_NODE_MANIFEST')
    expect(workflow).toContain("AGENTOS_REUSE_EXISTING_NODE_MANIFEST: 'true'")
    expect(releaseScript).toContain('reusablePublishedManifestAsset')
    expect(releaseScript).toContain('materializePublishedManifest')
    expect(releaseScript).toContain('Accept: application/octet-stream')
    const manifestReuse = releaseScript.slice(
      releaseScript.indexOf('if (hasNodeAssets && !dryRun)'),
      releaseScript.indexOf('// stage-only 上传的 manifest')
    )
    expect(manifestReuse.match(/Accept: application\/octet-stream/g)).toHaveLength(1)
    expect(manifestReuse).not.toContain('release download')
    expect(manifestReuse).not.toContain('browser_download_url')
    expect(releaseScript).not.toContain("['release', 'create', tag, ...assets")
    const pkg = JSON.parse(readFileSync('package.json', 'utf8'))
    expect(pkg.build.afterAllArtifactBuild).toBe('build/after-all-artifact-build.cjs')
    expect(pkg.build.afterPack).toBeUndefined()
    expect(pkg.build.mac.hardenedRuntime).toBe(true)
    expect(pkg.build.mac.notarize).toBeUndefined()
    expect(pkg.build.mac.entitlements).toBe('build/entitlements.mac.plist')
    expect(pkg.build.mac.entitlementsInherit).toBe('build/entitlements.mac.plist')
    const siteRelease = JSON.parse(readFileSync(`docs/releases/${pkg.version}.json`, 'utf8'))
    expect(siteRelease.version).toBe(pkg.version)
    expect(siteRelease.changelog.length).toBeGreaterThan(0)
  })

  it('Linux ARM64 deb 使用原生 dpkg-deb 并重写同源桌面 manifest', () => {
    const source = readFileSync('scripts/build-linux-deb.cjs', 'utf8')
    expect(source).toContain("process.platform !== 'linux' || process.arch !== 'arm64'")
    expect(source).toContain("execFileSync('dpkg-deb'")
    expect(source).toContain("'--root-owner-group'")
    expect(source).toContain('linux-arm64-unpacked')
    expect(source).toContain('writeDesktopReleaseManifest')
    expect(source).toContain('latest-linux-arm64.yml')
    expect(source).toContain('0o4755')
  })

  it('aggregate manifest 与发布后验收都强制五个平台齐套', () => {
    const manifestScript = readFileSync('scripts/generate-node-release-manifest.cjs', 'utf8')
    const publicCheck = readFileSync('scripts/check-public-node-release.cjs', 'utf8')
    for (const platform of ['mac-arm64', 'mac-x64', 'linux-arm64', 'linux-x64', 'win-x64']) {
      expect(manifestScript).toContain(`'${platform}'`)
      expect(publicCheck).toContain(`'${platform}'`)
    }
    expect(manifestScript).toContain('节点 Release 必须一次齐全五个平台')
    expect(manifestScript).toContain('source revision 与当前构建不一致')
    expect(manifestScript).toContain('provenance')
    expect(publicCheck).toContain("method: 'HEAD'")
    expect(publicCheck).toContain('fileIntegrityVerified === true')
  })

  it('Docker 远程节点验收从 SHA 锚定一行命令安装真实制品并覆盖换票、采纳与 PTY I/O', () => {
    const pkg = JSON.parse(readFileSync('package.json', 'utf8'))
    expect(pkg.scripts['test:remote-node']).toContain('test-remote-node-docker.cjs')
    const runner = readFileSync('scripts/test-remote-node-docker.cjs', 'utf8')
    expect(runner).toContain('`AGENT_OS_VERSION=${version}`')
    expect(runner).toContain('node scripts/build-node-dist.cjs')
    expect(runner).toContain('AGENT_OS_NODE_TEST_IMAGE')
    expect(runner).toContain('AGENT_OS_NODE_TEST_ARCHIVE: archivePath')
    expect(runner).toContain('AGENT_OS_NODE_TEST_PLATFORM: platform')
    expect(runner).toContain('AGENT_OS_NODE_TEST_VERSION: version')
    expect(runner).toContain('buildImageWithRetry')
    expect(runner).toContain("execFileSync('docker', [")
    const dockerfile = readFileSync('docker/remote-node/Dockerfile', 'utf8')
    expect(dockerfile).toContain('FROM node:20-bookworm-slim')
    expect(dockerfile).toContain('ARG AGENT_OS_VERSION=0.0.0-dev')
    expect(dockerfile).toContain('rm -rf /usr/local/bin/node /usr/local/bin/npm /usr/local/bin/npx')
    expect(dockerfile).toContain('CMD ["/usr/local/bin/run-agentos-installer-fixture"]')
    expect(dockerfile).toContain('/usr/local/bin/systemctl')
    expect(dockerfile).toContain('AGENT_OS_NODE_ASSET=/fixture/agentos-node.tar.gz')
    expect(dockerfile).not.toContain('npm install')
    expect(dockerfile).not.toContain('python3 make g++')
    expect(dockerfile).not.toContain('AGENT_OS_NODE_VERSION=0.2.7')
    const renderer = readFileSync('scripts/render-node-enroll-fixture.ts', 'utf8')
    expect(renderer).toContain('oneLiners(params).unix')
    expect(renderer).toContain('unixInstallScript(params)')
    const fixtureCommand = readFileSync('docker/remote-node/fixture-command.sh', 'utf8')
    expect(fixtureCommand).toContain('exec /usr/bin/curl "$@"')
    expect(fixtureCommand).toContain('"$prefix/agentos-node"')
    expect(fixtureCommand).not.toContain('"status":"registered"')
    const reverse = readFileSync('docker/remote-node/test-reverse.mjs', 'utf8')
    expect(reverse).toContain('const EXPECTED_PROTOCOL_VERSION = 10')
    expect(reverse).toContain('register.protocolVersion !== EXPECTED_PROTOCOL_VERSION')
    expect(reverse).toContain("type: 'enrollment-accepted'")
    expect(reverse).toContain("confirmation.type !== 'enrollment-confirmed'")
    expect(reverse).toContain(
      'const registered = tokenConfirmed && adopted && activeSocket?.readyState === 1'
    )
    expect(reverse).toContain("status: registered ? 'registered' : 'pending'")
    expect(reverse).toContain('AGENT_OS_EXPECTED_NODE_TOKEN=${LONG_NODE_TOKEN}')
    expect(reverse).toContain('long node token persisted and short enrollment token removed')
    const runInstaller = readFileSync('docker/remote-node/run-installer.sh', 'utf8')
    expect(runInstaller).toContain('grep -Fqx "AGENT_OS_NODE_TOKEN=$AGENT_OS_EXPECTED_NODE_TOKEN"')
    expect(runInstaller).toContain('! command -v gcc >/dev/null 2>&1')
    expect(runInstaller).toContain("if grep -q '^AGENT_OS_ENROLL_TOKEN='")
    expect(reverse).toContain("rpc('probeTerminal', [])")
    expect(reverse).toContain("type: 'node-adopted'")
    expect(reverse).toContain("rpc('createSession'")
    expect(reverse).toContain("rpc('write'")
  })
})
